# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-23 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingpreference',
            name='mail_chimp_subscribed',
            field=models.NullBooleanField(),
        ),
    ]
